### ISSUE TITLE
Ошибка парсинга при командах

### ISSUE THREAD

**Issue by Er2n** [GyverLibs/FastBot2#1]
Лонг пул потрясающий. Самое то для проектов где команды редко прилетают и не хочется сильно сеть грузить. Но либа пока очень сырая, например при отправке в бота команды со слешом, ошибка парсинга прилетает. (Появляется при всех режимах, не только long pool)

**Comment by GyverLibs** [comment]
Все проблемы списком пожалуйста, будут быстрее решаться))

**Comment by Er2n** [comment]
Пока только это нашел, ну и еще skipUpdates не все обновления пропускает, оставляет одно последнее. Но это хз как фиксить, если тг так реагирует на offset=-1.

**Comment by GyverLibs** [comment]
Да, оффсет -1 не всё скидывает, подарки от Пашки

**Comment by GyverLibs** [comment]
с командой проблема в GSON библиотеке, сейчас зафикшу

**Comment by Er2n** [comment]
![изображение](https://github.com/GyverLibs/FastBot2/assets/86849564/96b2dfee-0b8d-4b1e-96fe-cb25fea73b67)
Ему нолик не нравится.

**Comment by GyverLibs** [comment]
я знаю, поэтому и написал сейчас пофикшу)

**Comment by Er2n** [comment]
Крутяк, спасибо за скоростное исправление))
