### ISSUE TITLE
Библиотека не работает с TinyGsm

### ISSUE THREAD

**Issue by Shatodor** [GyverLibs/FastBot2#16]
Использовал код из примера для ESP32 c модемом SIM7000, но с ним  тестовый пример minimal не работает. Через Wi-FI все ок.
В чем может быть причина?

```
// версия с другим клиентом, например tinygsm
#define TINY_GSM_MODEM_SIM7000
#include <TinyGsmClient.h>
TinyGsm modem(Serial);
TinyGsmClient gsmclient(modem);
#include <FastBot2Client.h>
FastBot2Client` bot(gsmclient);
```

**Comment by GyverLibs** [comment]
Не знаю, внешний клиент не тестировался

**Comment by Shatodor** [comment]
В какую сторону копать посоветуете?

**Comment by GyverLibs** [comment]
Протестировать отдельно работу gsm, поделать запросы на сайты

**Comment by Shatodor** [comment]
Нужно было использовать:

`#define TINY_GSM_MODEM_SIM7000SSL`

**Comment by GyverLibs** [comment]
Ну, хорошо. Там вроде документация обширная, вся инфа есть

**Comment by LittleBuster** [comment]
> Нужно было использовать:
> 
> `#define TINY_GSM_MODEM_SIM7000SSL`

После этого нормально заработало? А какой оператор?
Пробовал на Билайне на SIM900L там ужасно медленная скорость передачи данных через GPRS, даже обычные HTTP заголовки по полчаса грузило

**Comment by Shatodor** [comment]
> > Нужно было использовать:
> > `#define TINY_GSM_MODEM_SIM7000SSL`
> 
> После этого нормально заработало? А какой оператор? Пробовал на Билайне на SIM900L там ужасно медленная скорость передачи данных через GPRS, даже обычные HTTP заголовки по полчаса грузило

Да, нормально. МТС

**Comment by GyverLibs** [comment]
добавить в доку/примеры? Больше изменений в работе с tinygsm нету?

**Comment by Shatodor** [comment]
> добавить в доку/примеры? Больше изменений в работе с tinygsm нету?

Было бы полезно указать, что для работы Телеграмма требуется защищенное соединение. Через Wi-Fi оно по умолчанию работает, а через GPRS нет.

**Comment by GyverLibs** [comment]
что нужно для того чтобы оно работало, что указать в доке?

**Comment by Shatodor** [comment]
Чтобы заработал FastBot2 для моего модема было достаточно  ` TINY_GSM_MODEM_SIM7000` заменить на ` TINY_GSM_MODEM_SIM7000SSL`. Как для других модемов не знаю.
Возможно даст наводку, то что у меня получилось отправлять HTTPS запросы через GPRS используя: 
```
TinyGsmClientSecure client(modem);
HttpClient http(client, server, port);
```
