### ISSUE TITLE
Бесконечный рестарт (команда не считается прочитанной ботом)

### ISSUE THREAD

**Issue by Shatodor** [GyverLibs/FastBot2#19]
Отправляю из ТГ команду "/restart", получаю ответ "Запущена перезагрузка устройства". ESP перезагружается, но после перезагрузки снова получает команду "/restart". В итоге бесконечный цикл перезагрузки. Ниже обработчик команды.  Можно как-то сделать команду принудительно прочитанной? 

```
        case SH("/restart"): {
            fb::Message msg;
            msg.chatID = chat_id;
            msg.text = "Запущена перезагрузка устройства";
            bot.sendMessage(msg);
            DBG(msg.text);
            ESP.restart();
        } break;
```

**Comment by GyverLibs** [comment]
См доку, для рестарта отдельный метод
