### ISSUE TITLE
Просьба в дополнении примеров

### ISSUE THREAD

**Issue by woodlist** [GyverLibs/FastBot2#23]
Пожалуйста, добавьте Replykeyboard пример.

**Comment by GyverLibs** [comment]
Есть в доке и примере test

**Comment by woodlist** [comment]
Да, действительно запрашиваемый пример был в menu. Путаница у меня возникла из за терминологии. У всех других поставщиков библиотек оно называется Reply Keyboard, у Вас называется "Большая клавиратура".

**Comment by woodlist** [comment]
С удовлетворением хочу отметить, что Ваша библиотека единственная рабочая среди прочих схожих после обновлении Ardunio IDE до последней версии и JSON.

**Comment by GyverLibs** [comment]
Потому что я использую свой стек библиотек и не завишу от чьих то обновлений :)

**Comment by woodlist** [comment]
Маэстро, раз так получилось, что мы ведем беседу на закрытой ветке, не отвлекая других, задам такой вопрос.
`fb::InlineMenu menu("kek 1 ; kek 2 ; kek 3 \n kek 4 ; kek 5", "test;pest;lol;https://www.google.ru/;https://www.yandex.ru/");`
имеет аналог для `Replykeyboard?`
Я попытался по хешу обработать нажатие на кнопки, но не получилось.

**Comment by GyverLibs** [comment]
Reply keyboard имеет только текст на кнопке, его же отправляет при нажатии просто в чат

**Comment by woodlist** [comment]
Как жаль... А это будет трудно наделить его таким желанным свойством?

**Comment by GyverLibs** [comment]
Думаю да. Нужно написать Пашке Дурову и убедить его, что у reply keyboard не хватает коллбэков

**Comment by woodlist** [comment]
Ах этот проказник Павел виноват? Тогда снимаю вопрос.

**Comment by woodlist** [comment]
Шутка шуткой, но просветите пожалуйста. Получается нажатие Reply кнопки вызывает действие только в пределах окна бота и ESP32 ни принимает и не сможет обработать такое нажатие?

**Comment by GyverLibs** [comment]
Нажатие reply keyboard просто отправляет текст с кнопки в чат с ботом, этот текст обрабатывается как обычное сообщение

**Comment by GyverLibs** [comment]
Об этом написано в документации в первом же абзаце

https://github.com/GyverLibs/FastBot2/blob/main/docs/6.menu.md

**Comment by woodlist** [comment]
Спасибо большое. У меня все получилось. И код загрузки удивительно небольшое и скорость взаимодействия с Телеграмом впечатляющий. Маэстро, как можно начислять Вам деньги на кружку ядреного пива, с рыбкой на закуску? Пожалуйста, только международный способ.

**Comment by GyverLibs** [comment]
Только то что по ссылке в шапке репозитория, международных наверное нету. Хотя boosty может принимает

**Comment by woodlist** [comment]
Маэстро, проверьте Бусти. Кажется получился.

**Comment by GyverLibs** [comment]
Спасибо, получил
