### ISSUE TITLE
в примере маленькая опечатка, русские буквы корректно не выводятся.

### ISSUE THREAD

**Issue by MaxKUlish1** [GyverLibs/FastBot2#3]
// эхо, вариант 2
        bot.sendMessage(u.message().text().str(), u.message().chat().id());
        
нужно заменить на 

 // эхо, вариант 2
        bot.sendMessage(u.message().text().toString(true), u.message().chat().id());

**Comment by GyverLibs** [comment]
Это не опечатка. Если нужно декодирование кириллицы - его нужно указать самостоятельно
