### ISSUE TITLE
Не работает skipUpdates.

### ISSUE THREAD

**Issue by vvzvlad** [GyverLibs/FastBot2#31]
В setup делаю 
```
    bot.skipUpdates(-10);
    bot.attachUpdate(updateh);
    bot.setToken(bot_token);
    bot.setPollMode(fb::Poll::Long, 20000);
```
Выключаю устройство, пишу команду, включаю устройство, присылает ответ на команду. Правда, у меня он мониторит не личку, а группу, но насколько я понимаю, эта функция должна пропускать любые сообщения.

**Comment by GyverLibs** [comment]
[Вот из доки](https://core.telegram.org/bots/api#getupdates)

> The negative offset can be specified to retrieve updates starting from -offset update from the end of the updates queue. All previous updates will be forgotten.

**Comment by vvzvlad** [comment]
Все еще не понимаю. Я пробовал: -1, -10, 0, 10 — и все еще как минимум одно сообщение обрабатывается. Мне надо сделать простую вещь — сбросить очередь сообщений при запуске.

**Comment by GyverLibs** [comment]
Можно сбросить все кроме последнего

**Comment by vvzvlad** [comment]
> Можно сбросить все кроме последнего

в смысле, любая из "-1, -10, 0" сбрасывает? Тогда почему у меня продолжают приходить сообщения?

**Comment by GyverLibs** [comment]
-1 сбрасывает все кроме последнего. Настойка применяется после следующего запроса getUpdates

**Comment by vvzvlad** [comment]
Тогда как мне пропустить все, что есть на сервере? 

```
    bot.setPollMode(fb::Poll::Long, 20000);
    bot.skipUpdates(0);
    bot.getUpdates(true);
    bot.setToken(bot_token);
    bot.attachUpdate(updateh);
```
Так получается?

**Comment by GyverLibs** [comment]
Нет, 0 не работает, нужен -1

**Comment by vvzvlad** [comment]
```
    bot.setPollMode(fb::Poll::Long, 20000);
    bot.skipUpdates(-1);
    bot.getUpdates(true);
    bot.setToken(bot_token);
    bot.attachUpdate(updateh);
```
Оставляет одно сообщение, последнее. А как пропустить все?

**Comment by GyverLibs** [comment]
Получается никак, надо игнорировать один апдейт
